# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 04:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeWrong', models.TimeField(verbose_name='How Long Was Gerald Wrong')),
                ('Subject', models.CharField(max_length=100, verbose_name='Enter The Topic Gerald Was Wrong About')),
                ('Details', models.CharField(max_length=500)),
                ('DateTime', models.DateTimeField(default=datetime.datetime(2017, 8, 10, 4, 32, 51, 413059, tzinfo=utc))),
            ],
        ),
    ]
