# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 05:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wrong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 10, 5, 28, 3, 240850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='TimeWrong',
            field=models.IntegerField(verbose_name='How Long Was Gerald Wrong'),
        ),
    ]
