# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 05:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wrong', '0002_auto_20170810_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 10, 5, 30, 39, 617472, tzinfo=utc)),
        ),
    ]
