# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 05:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quote', models.CharField(max_length=999)),
                ('Subject', models.CharField(max_length=999)),
                ('DateTime', models.DateField(default=datetime.datetime(2017, 8, 19, 5, 9, 3, 138930, tzinfo=utc))),
            ],
        ),
    ]
