# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 05:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='DateTime',
            field=models.DateField(default=datetime.datetime(2017, 8, 19, 5, 17, 32, 643676, tzinfo=utc)),
        ),
    ]
