# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20170819_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='DateTime',
            field=models.DateField(default=datetime.datetime(2017, 8, 19, 16, 33, 6, 516989, tzinfo=utc), verbose_name='Date: '),
        ),
    ]
